---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: check-ast
          - id: requirements-txt-fixer
            files: (.*)requirements(.*).txt$
          - id: end-of-file-fixer
          - id: double-quote-string-fixer
          - id: check-added-large-files
            types: [file, python]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-yapf
      rev: v0.32.0
      hooks:
          - id: yapf
    - repo: https://github.com/codespell-project/codespell
      rev: v2.1.0
      hooks:
          - id: codespell
    - repo: https://github.com/Calinou/pre-commit-luacheck
      rev: v1.0.0
      hooks:
          - id: luacheck
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.26.3
      hooks:
          - id: yamllint
            args: [-d, relaxed]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
